branch-defaults:
  default:
    environment: null
    group_suffix: null
  main:
    environment: your-environment-name
  master:
    environment: test-eb
environment-defaults:
  your-environment-name:
    branch: null
    repository: null
global:
  application_name: test-eb
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.9
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: dev
  repository: null
  sc: git
  workspace_type: Application
