# Generated by Django 4.2.7 on 2024-11-27 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturer",
            name="location",
            field=models.TextField(default=" "),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="manufacturer.manufacturer",
            ),
        ),
    ]
