# Generated by Django 4.2.7 on 2024-11-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturer", "0002_manufacturer_location_alter_product_manufacturer"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
